server:
  port: 8082

spring:
  application:
    name: bookmyshow-application
  db1:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/bookmyshow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  db2:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/oauth_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: TRACE