server:
  port: 8082

spring:
  application:
    name: bookmyshow-application
  db1:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/bookmyshow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  db2:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/oauth_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: TRACE


app:
  encryption:
    key: ${ENCRYPTION_KEY}
  dbencryption:
    key: ${DBENCRYPTION_KEY}
  base-url: /app/librarymanagement
  notifications:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID}
      service-sid: ${TWILIO_SERVICE_SID}
      auth-token: ${TWILIO_AUTH_TOKEN}
    baseUrl: https://verify.twilio.com/v2/Services
    sendOtp:
      url: /{serviceSid}/Verifications
    verifyOtp:
      url: /{serviceSid}/VerificationCheck
  user:
    create-user: /createUser
    sendOtp: /sendOtp
    verifyOtp: /verifyOtp
