server:
  port: 8082

spring:
  application:
    name: bookmyshow-application
  db1:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/bookmyshow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: PrimaryDB-Pool
  db2:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/oauth_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: OAuthDB-Pool
  jpa:
    hibernate:
      ddl-auto: validate # safe in production if we add any column or new table it will fail fast application at startup change validate to update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: TRACE


app:
  encryption:
    key: ${ENCRYPTION_KEY}
  dbencryption:
    key: ${DBENCRYPTION_KEY}
  base-url: /app/librarymanagement
  notifications:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID}
      service-sid: ${TWILIO_SERVICE_SID}
      auth-token: ${TWILIO_AUTH_TOKEN}
    baseUrl: https://verify.twilio.com/v2/Services
    sendOtp:
      url: /{serviceSid}/Verifications
    verifyOtp:
      url: /{serviceSid}/VerificationCheck
  user:
    create-user: /createUser
    sendOtp: /sendOtp
    verifyOtp: /verifyOtp
